name: Build and Deploy Quartz Site
on:
  workflow_dispatch:
  push:
    branches:
      - v4 # or whatever your main branch is named

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4

      - name: âœ¨ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: âœ¨ Install Dependencies
        run: |
          npm ci
          npm list

      - name: ğŸ› ï¸ Build Quartz Site
        run: |
          echo "Building site..."
          npx quartz build
          echo "Build complete. Contents of public directory:"
          ls -la public

      - name: ğŸ”‘ Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: ğŸš€ Deploy with rsync
        run: |
          rsync --archive --delete --stats 'public/' nedge@202.61.247.130/home/nedge/apps/quartz-obsidian-publish/public/

      - name: ğŸ³ Restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            docker-compose -f /home/***/apps/quartz-obsidian-publish/docker-compose.yml up -d --force-recreate
